name = "toolboxs"
compatibility_date = "2026-05-23"
pages_build_output_dir = "./"

[[kv_namespaces]]
binding = "MY_KV"
id = "b4e04b3f55904a018aec459dd412cd05"
preview_id = "b4e04b3f55904a018aec459dd412cd05"