@echo off
chcp 65001 >nul
echo 正在拉取远端最新代码...
git pull
echo 正在添加所有变更文件...
git add .
set /p commitMsg=请输入提交备注：
echo 正在提交代码...
git commit -m "%commitMsg%"
echo 正在推送到远程仓库...
git push
echo 代码推送完成，按任意键退出...
pause >nul